test:
	NODE_ENV=test ./node_modules/.bin/mocha --reporter spec --recursive spec/spec_helper.js spec/

test-d:
	NODE_ENV=test ./node_modules/.bin/mocha debug --reporter spec --recursive spec/spec_helper.js spec/

.PHONY: test
